---
title: "shiny for iris"
author: "Debojyoti Das"
date: "1/16/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r pressure, echo=FALSE}
library(shiny)

# Define UI for miles per gallon app ----
ui <- pageWithSidebar(
  
  # App title ----
  headerPanel("Iris data"),
  
  # Sidebar panel for inputs ----
  sidebarPanel(
    
    # Input: Selector for variable to plot against mpg ----
    selectInput("variable", "Variable:", 
                c("Sepal Length" = "Sepal.Length",
                  "Sepal Width" = "Sepal.Width",
                  "Petal Length" = "Petal.Length",
                  "Petal Width" = "Petal.Width")),
    
    # Input: Checkbox for whether outliers should be included ----
    checkboxInput("outliers", "Show outliers", TRUE)
    
  ),
  
  # Main panel for displaying outputs ----
  mainPanel(
    
    # Output: Formatted text for caption ----
    h3(textOutput("caption")),
    
    # Output: Plot of the requested variable ----
    plotOutput("irisPlot"),
    
    # h3(textOutput("histo")),
    
    # Output: Histogram of the requested variable  ----
    plotOutput("irisHistogram")
    
  )
)


# Define server logic to plot various variables against mpg ----
server <- function(input, output) {
  
  # Compute the formula text ----
  # This is in a reactive expression since it is shared by the
  # output$caption and output$irisPlot aand output$irisHistogram functions
  formulaText <- reactive({
    paste(input$variable, " ~ Species")
  })
  
  dependentVariable <- reactive({
    input$variable
  })
  # Return the formula text for printing as a caption ----
  output$caption <- renderText({
    formulaText()
  })
  
  # Generate a plot of the requested variable ----
  
  output$irisPlot <- renderPlot({
    
    #create boxplot
    boxplot(as.formula(formulaText()),
            data=iris,
            # main='Sepal Length by Species',
            xlab='Species',
            ylab=dependentVariable(),
            col=c("red", "blue", "green"),
            border='black')
  
  })
  
  data2plot <- reactive({
    as.vector(unlist(iris[dependentVariable()]))
    })
  
  
  output$irisHistogram <- renderPlot({
    #create boxplot
    hist(data2plot(), xlab = dependentVariable(), main = dependentVariable())
  })
  

}

shinyApp(ui, server)

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
